on:
    workflow_dispatch:
    schedule:
        - cron: "*/2 * * * *" # Determines the scheduled interval for this workflow. This example runs every hour.

jobs:
    run-integration:
        runs-on: ubuntu-latest

        steps:
            - name: Run jira Integration
              uses: port-labs/ocean-sail@v1
              with:
                  type: jira
                  port_client_id: ${{ secrets.PORT_CLIENT_ID }}
                  port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
                  port_base_url: "https://api.getport.io"
                  config: |
                      jira_host: "https://testing-port.atlassian.net"
                      atlassian_user_email: ${{ secrets.atlassianUserEmail }}
                      atlassian_user_token: ${{ secrets.atlassianUserToken }}
