name: Update Open PRs in Repository Entity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update_repository_entity:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup jq
      uses: mikefarah/jq@v1
      with:
        tokens: true

    - name: Get PR count
      id: get_pr_count
      run: |
        pr_count=$(gh pr list --json number | jq '. | length')
        echo "pr_count=$pr_count" >> $GITHUB_ENV
        echo "::set-output name=pr_count::$pr_count"

    - name: Display PR count
      run: echo "There are ${{ steps.get_pr_count.outputs.pr_count }} open pull requests."

    - name: Construct JSON Properties
      id: construct_json
      run: |
        pr_count=${{ steps.get_pr_count.outputs.pr_count }}
        properties=$(jq -n --arg pr_count "$pr_count" '{open_pr_count: $pr_count | tonumber}')
        echo "::set-output name=properties::$properties"

    - name: Update Port Entity
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
        operation: UPSERT
        identifier: portapp
        title: portapp
        blueprint: repository
        properties: ${{ steps.construct_json.outputs.properties }}
