name: Update Open PRs in matching repository entity 
on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '* */6 * * *'  

jobs:
  update-open-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Count open PRs
        id: count_prs
        run: |
          PR_COUNT=$(curl -s -H "Authorization: token ${{ secrets.MY_PAT_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | jq '. | length')
          echo "PR_COUNT=$PR_COUNT" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}

      - name: Get access token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' --header 'Content-Type: application/json' --data-raw '{
          "clientId": "yzmbLEy9Ufs5sNdpuFXMLkE6zMHegUr7",
          "clientSecret": "R5p3elPBwU0uvpJSmt1QFx83BPFAFvq0Rw84sDIthwWHNvQb7Y7PL5qoazlyOKMD"
          }' | jq -r '.accessToken')

      - name: Update Port Entity
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          BLUEPRINT_IDENTIFIER="repository"
          OPEN_PR_COUNT="portapp"

          # Prepare JSON data
          JSON_DATA=$(cat <<EOF
          {
            "identifier": "$REPO_NAME",
            "title": "$REPO_NAME",
            "properties": {
              "open_pr_count": $PR_COUNT
            },
            "relations": {}
          }
          EOF
          )

          # Send request to Port
          curl --location --request PATCH \
               --url "https://api.getport.io/v1/blueprints/$BLUEPRINT_IDENTIFIER/entities/$OPEN_PR_COUNT" \
               --header "Authorization: Bearer $access_token" \
               --header "Content-Type: application/json" \
               --data "$JSON_DATA"
        env:
          PR_COUNT: ${{ steps.count_prs.outputs.PR_COUNT }}
