name: Update Open PRs in matching repository entity 
on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '* */6 * * *'  

jobs:
  count-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Get PR count
      id: get-pr-count
      run: |
        pr_count=$(gh pr list --json number | jq '. | length')
        echo "pr_count=${pr_count}" >> $GITHUB_ENV

    - name: Use PR count
      run: echo "There are ${{ env.pr_count }} open pull requests."
      env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}

    - name: Update Port Entity
    - uses: port-labs/port-github-action@v1
      with:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          operation: UPSERT
          identifier: portapp
          title: portapp
          blueprint: repository
          properties: |
              {
                "open_pr_count: {{ env.pr_count }}
              }
      env:
          PR_COUNT: ${{ steps.count_prs.outputs.PR_COUNT }}
